### ISSUE TITLE
Chase Center Showing Oracle Park Events

### ISSUE THREAD

**Issue by kennethshsu** [albertyw/chase-center-calendar#24]
I am currently seeing all Oracle Park events on the Chase Center calendar [here](https://www.chasecentercalendar.com). Is there a bad commit recently?

Thanks for keeping this alive, I use these calendars very often.

**Comment by albertyw** [comment]
Fixed in eacee4a

Thanks for the bug report.

**Comment by albertyw** [comment]
It'll probably take a few minutes for the google calendar caches to update with the fixed events

**Comment by kennethshsu** [comment]
No problem, I'll report back if that doesn't fix it. Thanks!
